palette = "flexoki"
add_newline = true

format = """
[$username$hostname](muted)\
[ :: ](faint)\
$directory\
[ :: ](faint)\
$git_branch\
$git_status\
$line_break\
$character"""

right_format = "$golang$rust$c$lua$nodejs$python$jobs$cmd_duration$status"

[palettes.flexoki]
bg      = "#100F0F"
text    = "#CECDC3"
muted   = "#878580"
faint   = "#575653"
red     = "#D14D41"
orange  = "#DA702C"
yellow  = "#D0A215"
green   = "#879A39"
cyan    = "#3AA99F"
blue    = "#4385BE"
purple  = "#8B7EC8"
magenta = "#CE5D97"

[username]
show_always = false
style_user = "muted"
format = "[$user]($style)"

[hostname]
ssh_only = true
style = "muted"
format = "[@$hostname]($style)"

[directory]
style = "text"
format = "[$path]($style)"

[git_branch]
symbol = ""
style = "purple"
format = "[$branch]($style) "

[git_status]
style = "yellow"
format = "[$all_status$ahead_behind]($style)"
modified = "~${count}"
staged = "+${count}"
untracked = "?${count}"
deleted = "×${count}"
conflicted = "!${count}"

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"

[golang]
symbol = "go "
style = "cyan"
format = "[$symbol$version ]($style)"

[rust]
symbol = "rust "
style = "orange"
format = "[$symbol$version ]($style)"

[c]
symbol = "c "
style = "blue"
format = "[$symbol$name ]($style)"

[lua]
symbol = "lua "
style = "blue"
format = "[$symbol$version ]($style)"

[nodejs]
symbol = "node "
style = "green"
format = "[$symbol$version ]($style)"

[python]
symbol = "py "
style = "yellow"
format = "[$symbol$version ]($style)"

[jobs]
symbol = "jobs "
style = "purple"
format = "[$symbol$number ]($style)"

[cmd_duration]
min_time = 2000
style = "muted"
format = "[$duration ]($style)"

[status]
disabled = false
style = "red"
format = "[exit $status]($style)"
