# ------------------------------------------------------------
# Kitty
# ------------------------------------------------------------
font_family IMWriting Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_size 13.0


window_padding_width 6

scrollback_lines 10000

cursor_shape beam

macos_option_as_alt left

# ============================================================
# Horizon
# ============================================================

background              #1C1E26
foreground              #D5D8DA

selection_background    #2E303E
selection_foreground    #F2F2F2

cursor                   #E95678
cursor_text_color        #1C1E26

url_color                #59E3E3

# Black
color0   #16161C
color8   #6C6F93

# Red
color1   #E95678
color9   #EC6A88

# Green
color2   #29D398
color10  #3FDAA4

# Yellow
color3   #FAB795
color11  #FBC3A7

# Blue
color4   #26BBD9
color12  #3FC6DE

# Magenta
color5   #EE64AE
color13  #F075B7

# Cyan
color6   #59E3E3
color14  #6BE6E6

# White
color7   #D5D8DA
color15  #F2F2F2
