# ------------------------------------------------------------
# Kitty
# ------------------------------------------------------------

# typography
font_family IMWriting Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_size 14.5

# spacing
window_padding_width 8

# cursor
cursor_shape beam

scrollback_lines 10000

# macOS
macos_option_as_alt left

# ============================================================
# Flexoki Dusk
# ============================================================

background #17181C
foreground #CECDC3

selection_background #2A2D34
selection_foreground #FFFCF0

cursor #4CB4AB
cursor_text_color #17181C

url_color #4CB4AB

color0  #17181C
color8  #5E6068

color1  #D14D41
color9  #F89A8A

color2  #879A39
color10 #BEC97E

color3  #D0A215
color11 #ECCB60

color4  #5B8FC4
color12 #92BFDB

color5  #9A8DD0
color13 #C4B9E0

color6  #4CB4AB
color14 #87D3C3

color7  #CECDC3
color15 #FFFCF0

