# ------------------------------------------------------------
# Kitty
# ------------------------------------------------------------
font_family IMWriting Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto

font_size 13.0


window_padding_width 6

scrollback_lines 10000

cursor_shape beam

macos_option_as_alt left

# ------------------------------------------------------------
# Flexoki Dark — XD Version
# ------------------------------------------------------------

background              #100F0F
foreground              #CECDC3

selection_background    #403E3C
selection_foreground    #FFFCF0

cursor                   #CECDC3
cursor_text_color        #100F0F

url_color                #3AA99F

# black / gray
color0   #100F0F
color8   #878580

# red
color1   #D14D41
color9   #F89A8A

# green
color2   #879A39
color10  #BEC97E

# yellow
color3   #D0A215
color11  #ECCB60

# blue
color4   #4385BE
color12  #92BFDB

# magenta / purple
color5   #8B7EC8
color13  #C4B9E0

# cyan
color6   #24837B
color14  #3AA99F

# white
color7   #CECDC3
color15  #FFFCF0

